/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";

export const ActionStatus: core.serialization.Schema<serializers.ActionStatus.Raw, Credal.ActionStatus> =
    core.serialization.enum_([
        "PENDING_APPROVAL",
        "IN_PROGRESS",
        "APPROVED_SUCCEEDED",
        "APPROVED_FAILED",
        "NO_APPROVAL_NEEDED_SUCCEEDED",
        "NO_APPROVAL_NEEDED_FAILED",
    ]);

export declare namespace ActionStatus {
    type Raw =
        | "PENDING_APPROVAL"
        | "IN_PROGRESS"
        | "APPROVED_SUCCEEDED"
        | "APPROVED_FAILED"
        | "NO_APPROVAL_NEEDED_SUCCEEDED"
        | "NO_APPROVAL_NEEDED_FAILED";
}
