/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";

export const Conversation: core.serialization.ObjectSchema<serializers.Conversation.Raw, Credal.Conversation> =
    core.serialization.object({
        conversationId: core.serialization.string(),
    });

export declare namespace Conversation {
    interface Raw {
        conversationId: string;
    }
}
