/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";
import { DirectMessage } from "./DirectMessage";
import { SlackThread } from "./SlackThread";
import { Conversation } from "./Conversation";

export const HumanConfirmationChannel: core.serialization.Schema<
    serializers.HumanConfirmationChannel.Raw,
    Credal.HumanConfirmationChannel
> = core.serialization
    .union("type", {
        directMessage: DirectMessage,
        slackThread: SlackThread,
        conversation: Conversation,
    })
    .transform<Credal.HumanConfirmationChannel>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace HumanConfirmationChannel {
    type Raw =
        | HumanConfirmationChannel.DirectMessage
        | HumanConfirmationChannel.SlackThread
        | HumanConfirmationChannel.Conversation;

    interface DirectMessage extends DirectMessage.Raw {
        type: "directMessage";
    }

    interface SlackThread extends SlackThread.Raw {
        type: "slackThread";
    }

    interface Conversation extends Conversation.Raw {
        type: "conversation";
    }
}
