/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";

export const SlackThread: core.serialization.ObjectSchema<serializers.SlackThread.Raw, Credal.SlackThread> =
    core.serialization.object({
        channelId: core.serialization.string(),
        threadTimestamp: core.serialization.string(),
    });

export declare namespace SlackThread {
    interface Raw {
        channelId: string;
        threadTimestamp: string;
    }
}
