/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../index.js";

export interface DocumentMetadataPatchRequest {
    sources: Credal.DocumentMetadataPatch[];
    uploadAsUserEmail: string;
}
