/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";

export const CreateCollectionResponse: core.serialization.ObjectSchema<
    serializers.CreateCollectionResponse.Raw,
    Credal.CreateCollectionResponse
> = core.serialization.object({
    collectionId: core.serialization.string(),
});

export declare namespace CreateCollectionResponse {
    interface Raw {
        collectionId: string;
    }
}
