/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";

export const MongoSourceFieldsConfig: core.serialization.ObjectSchema<
    serializers.MongoSourceFieldsConfig.Raw,
    Credal.MongoSourceFieldsConfig
> = core.serialization.object({
    body: core.serialization.string(),
    sourceName: core.serialization.string(),
    sourceSystemUpdated: core.serialization.string().optional(),
    sourceUrl: core.serialization.string().optional(),
});

export declare namespace MongoSourceFieldsConfig {
    export interface Raw {
        body: string;
        sourceName: string;
        sourceSystemUpdated?: string | null;
        sourceUrl?: string | null;
    }
}
