/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../../index";

/**
 * @example
 *     {
 *         resourceIdentifiers: [{
 *                 type: "url",
 *                 url: "https://docs.google.com/document/d/170NrBm0Do7gdzvr54UvyslPVWkQFOA0lgNycFmdZJQr/edit"
 *             }, {
 *                 type: "external-resource-id",
 *                 externalResourceId: "sfsdfvr54UvyslPVWkQFOA0dfsdfsdflgNycFmdZJQr",
 *                 resourceType: "ZENDESK_TICKET"
 *             }],
 *         userEmail: "john.smith@foo.com"
 *     }
 */
export interface CheckBulkResourcesAuthorizationForUserRequest {
    /**
     * The set of resource identifier for which you want to check authorization. Currently limited to 20 resources.
     *
     */
    resourceIdentifiers: Credal.ResourceIdentifier[];
    /**
     * The user email to check authorization for.
     *
     */
    userEmail: string;
    /**
     * If specified, Credal will bypass the permissions cache and check current permissions for all resources specified.
     *
     */
    disableCache?: boolean;
}
