/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../../index.js";

/**
 * @example
 *     {
 *         userEmail: "john.smith@foo.com"
 *     }
 */
export interface ListCachedAuthorizedResourcesForUserRequest {
    /** The user email to list authorized resources for. */
    userEmail: string;
    /** The type of resource you want to list. If not specified, all resource types will be listed. */
    resourceType?: Credal.ResourceType;
    /** The maximum number of resources to return. Defaults to 100. */
    limit?: number;
    /** The offset to use for pagination. If not specified, the first page of results will be returned. */
    offset?: number;
}
