/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";
import { UserMetadataPatch } from "../types/UserMetadataPatch";

export const Request: core.serialization.Schema<serializers.users.metadata.Request.Raw, Credal.UserMetadataPatch[]> =
    core.serialization.list(UserMetadataPatch);

export declare namespace Request {
    export type Raw = UserMetadataPatch.Raw[];
}
