/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Credal from "../../../../../api/index";
import * as core from "../../../../../core";
import { ResourceIdentifier } from "../../../common/types/ResourceIdentifier";

export const CheckResourceAuthorizationForUserRequest: core.serialization.Schema<
    serializers.CheckResourceAuthorizationForUserRequest.Raw,
    Credal.CheckResourceAuthorizationForUserRequest
> = core.serialization.object({
    resourceIdentifier: ResourceIdentifier,
    userEmail: core.serialization.string(),
    disableCache: core.serialization.boolean().optional(),
});

export declare namespace CheckResourceAuthorizationForUserRequest {
    interface Raw {
        resourceIdentifier: ResourceIdentifier.Raw;
        userEmail: string;
        disableCache?: boolean | null;
    }
}
