/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Credal from "../../../../../api/index";
import * as core from "../../../../../core";
import { ResourceType } from "../../../common/types/ResourceType";

export const ListCachedAuthorizedResourcesForUserRequest: core.serialization.Schema<
    serializers.ListCachedAuthorizedResourcesForUserRequest.Raw,
    Credal.ListCachedAuthorizedResourcesForUserRequest
> = core.serialization.object({
    userEmail: core.serialization.string(),
    resourceType: ResourceType.optional(),
    limit: core.serialization.number().optional(),
    offset: core.serialization.number().optional(),
});

export declare namespace ListCachedAuthorizedResourcesForUserRequest {
    export interface Raw {
        userEmail: string;
        resourceType?: ResourceType.Raw | null;
        limit?: number | null;
        offset?: number | null;
    }
}
