/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class CredalTimeoutError extends Error {
    constructor(message: string) {
        super(message);
        Object.setPrototypeOf(this, CredalTimeoutError.prototype);
    }
}
