/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../index.js";

export interface ExternalResourceId {
    externalResourceId: string;
    resourceType: Credal.ResourceType;
}
