// This file was auto-generated by Fern from our API Definition.

export const Operator = {
    LessThan: "<",
    GreaterThan: ">",
    LessThanOrEqual: "<=",
    GreaterThanOrEqual: ">=",
    NotEqual: "!=",
    Equal: "==",
    Contains: "contains",
} as const;
export type Operator = (typeof Operator)[keyof typeof Operator];
