/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ResourceType =
    | "GOOGLE_DRIVE_ITEM"
    | "MICROSOFT_DRIVE_ITEM"
    | "ZENDESK_TICKET"
    | "ZENDESK_ARTICLE"
    | "ZENDESK_GROUP"
    | "ZENDESK_ARTICLE_SECTION"
    | "ZENDESK_ARTICLE_CATEGORY"
    | "CONFLUENCE_PAGE"
    | "CONFLUENCE_SPACE"
    | "JIRA_TICKET"
    | "JIRA_PROJECT"
    | "SALESFORCE_TASK"
    | "BOX_FILE"
    | "BOX_FOLDER"
    | "NOTION_PAGE"
    | "NOTION_DATABASE"
    | "SLACK_CHANNEL"
    | "MONGO_COLLECTION_SYNC"
    | "UNKNOWN";
export const ResourceType = {
    GoogleDriveItem: "GOOGLE_DRIVE_ITEM",
    MicrosoftDriveItem: "MICROSOFT_DRIVE_ITEM",
    ZendeskTicket: "ZENDESK_TICKET",
    ZendeskArticle: "ZENDESK_ARTICLE",
    ZendeskGroup: "ZENDESK_GROUP",
    ZendeskArticleSection: "ZENDESK_ARTICLE_SECTION",
    ZendeskArticleCategory: "ZENDESK_ARTICLE_CATEGORY",
    ConfluencePage: "CONFLUENCE_PAGE",
    ConfluenceSpace: "CONFLUENCE_SPACE",
    JiraTicket: "JIRA_TICKET",
    JiraProject: "JIRA_PROJECT",
    SalesforceTask: "SALESFORCE_TASK",
    BoxFile: "BOX_FILE",
    BoxFolder: "BOX_FOLDER",
    NotionPage: "NOTION_PAGE",
    NotionDatabase: "NOTION_DATABASE",
    SlackChannel: "SLACK_CHANNEL",
    MongoCollectionSync: "MONGO_COLLECTION_SYNC",
    Unknown: "UNKNOWN",
} as const;
