// This file was auto-generated by Fern from our API Definition.

export const ResourceType = {
    GoogleDriveItem: "GOOGLE_DRIVE_ITEM",
    MicrosoftDriveItem: "MICROSOFT_DRIVE_ITEM",
    ZendeskTicket: "ZENDESK_TICKET",
    ZendeskArticle: "ZENDESK_ARTICLE",
    ZendeskGroup: "ZENDESK_GROUP",
    ZendeskArticleSection: "ZENDESK_ARTICLE_SECTION",
    ZendeskArticleCategory: "ZENDESK_ARTICLE_CATEGORY",
    ConfluencePage: "CONFLUENCE_PAGE",
    ConfluenceSpace: "CONFLUENCE_SPACE",
    JiraTicket: "JIRA_TICKET",
    JiraProject: "JIRA_PROJECT",
    SalesforceTask: "SALESFORCE_TASK",
    BoxFile: "BOX_FILE",
    BoxFolder: "BOX_FOLDER",
    NotionPage: "NOTION_PAGE",
    NotionDatabase: "NOTION_DATABASE",
    SlackChannel: "SLACK_CHANNEL",
    MongoCollectionSync: "MONGO_COLLECTION_SYNC",
    Unknown: "UNKNOWN",
} as const;
export type ResourceType = (typeof ResourceType)[keyof typeof ResourceType];
