/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../index";

export type CheckBulkResourcesAuthorizationResponse = Credal.ResourceAuthorizationResult[];
