/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../index.js";

export type Principal = Credal.Principal.Group | Credal.Principal.User;

export namespace Principal {
    export interface Group extends Credal.Group {
        type: "group";
    }

    export interface User extends Credal.User {
        type: "user";
    }
}
