/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../index";

export type Principal = Credal.Principal.Group | Credal.Principal.User;

export declare namespace Principal {
    interface Group extends Credal.Group {
        type: "group";
    }

    interface User extends Credal.User {
        type: "user";
    }
}
