/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../index";

export interface ResourceAuthorizationResult {
    resourceIdentifier: Credal.ResourceIdentifier;
    authorized: boolean;
}
