/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../index";

export interface ResourceAuthorizationResult {
    externalResourceId: Credal.ExternalResourceId;
    inputUrl?: string;
    authorized: boolean;
}
