/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";
import { ResourceIdentifier } from "../../common/types/ResourceIdentifier";

export const DocumentMetadataPatch: core.serialization.ObjectSchema<
    serializers.DocumentMetadataPatch.Raw,
    Credal.DocumentMetadataPatch
> = core.serialization.object({
    resourceIdentifier: ResourceIdentifier,
    metadata: core.serialization.unknown(),
});

export declare namespace DocumentMetadataPatch {
    export interface Raw {
        resourceIdentifier: ResourceIdentifier.Raw;
        metadata?: unknown;
    }
}
