/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";

export const SyncSourceByUrlRequest: core.serialization.ObjectSchema<
    serializers.SyncSourceByUrlRequest.Raw,
    Credal.SyncSourceByUrlRequest
> = core.serialization.object({
    uploadAsUserEmail: core.serialization.string(),
    sourceUrl: core.serialization.string(),
});

export declare namespace SyncSourceByUrlRequest {
    interface Raw {
        uploadAsUserEmail: string;
        sourceUrl: string;
    }
}
