/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";

export const UploadDocumentResponse: core.serialization.ObjectSchema<
    serializers.UploadDocumentResponse.Raw,
    Credal.UploadDocumentResponse
> = core.serialization.object({
    documentId: core.serialization.string(),
});

export declare namespace UploadDocumentResponse {
    interface Raw {
        documentId: string;
    }
}
