/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../index";

export interface DocumentCollectionSearchResult {
    documentId: string;
    documentName: string;
    documentMetadata: Record<string, string>;
    chunks: Credal.SearchResultChunk[];
    mergedContents?: string;
}
