/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DocumentCollectionSearchOptions {
    /** The maximum number of chunks to return. Defaults to 10. */
    maxChunks?: number;
    /** Whether to merge the chunks for a document and just return one result per document. Defaults to false. */
    mergeContents?: boolean;
    /**
     * The similarity threshold between 0 and 1 for the search results. A higher number leads to fewer but more relevant results.
     * Defaults to 0.45.
     */
    threshold?: number;
    /** Whether to automatically filter the search results based on the user query and available metadata on the collection. Defaults to false. */
    enableSmartFiltering?: boolean;
    /** / Whether to extract search terms from the user query and use them for semantic search. Defaults to false. */
    enableQueryExtraction?: boolean;
    /** Whether to rerank the search results after the initial semantic search query. Defaults to false. */
    enableReranking?: boolean;
}
