// This file was auto-generated by Fern from our API Definition.

import type * as Credal from "../../../index.js";

export interface SearchDocumentCollectionResponse {
    searchTermsUsed: string[];
    structuredFiltersApplied: Credal.SingleFieldFilter[];
    searchId: string;
    results: Credal.DocumentCollectionSearchResult[];
}
