// This file was auto-generated by Fern from our API Definition.

export interface SearchResultChunk {
    chunkId: string;
    chunkIndex: number;
    text: string;
    /** The similarity score between 0 and 1 for the search result. A higher number means the chunk is more relevant to the search query. */
    score: number;
}
