// This file was auto-generated by Fern from our API Definition.

import type * as Credal from "../../../index.js";

export interface SingleFieldFilter {
    field: string;
    operator: Credal.Operator;
    value: string;
}
