/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../index";

export interface SingleFieldFilter {
    field: string;
    operator: Credal.Operator;
    value: string;
}
