/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../../index";

/**
 * @example
 *     {
 *         actionId: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
 *         userEmail: "string",
 *         requireHumanConfirmation: true,
 *         humanConfirmationChannel: {
 *             type: "directMessage",
 *             channelId: "string"
 *         },
 *         justification: "string",
 *         auditLogId: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"
 *     }
 */
export interface InvokeActionRequest {
    actionId: string;
    /**
     * The user who we should take the action on behalf of
     *
     */
    userEmail: string;
    /**
     * If true, then before executing the action we will ask for a human confirmation in Slack.  If false, we may still ask for human confirmation if it's required by your organization admin.
     *
     */
    requireHumanConfirmation?: boolean;
    /**
     * Where we should ask for human confirmation if necessary
     *
     */
    humanConfirmationChannel: Credal.HumanConfirmationChannel;
    /**
     * The justification for requesting this action.  This is likely generated by the LLM that requested the action.
     *
     */
    justification: string;
    /**
     * Audit log for the message that called for this action
     *
     */
    auditLogId: string;
}
