/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";

export const Action: core.serialization.Schema<serializers.Action.Raw, Credal.Action> = core.serialization.enum_([
    "READ",
]);

export declare namespace Action {
    export type Raw = "READ";
}
