/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";

export const CheckResourceAuthorizationResponse: core.serialization.ObjectSchema<
    serializers.CheckResourceAuthorizationResponse.Raw,
    Credal.CheckResourceAuthorizationResponse
> = core.serialization.object({
    authorized: core.serialization.boolean(),
});

export declare namespace CheckResourceAuthorizationResponse {
    export interface Raw {
        authorized: boolean;
    }
}
