/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";
import { ResourceAuthorizationResult } from "./ResourceAuthorizationResult";

export const CheckBulkResourcesAuthorizationResponse: core.serialization.Schema<
    serializers.CheckBulkResourcesAuthorizationResponse.Raw,
    Credal.CheckBulkResourcesAuthorizationResponse
> = core.serialization.list(ResourceAuthorizationResult);

export declare namespace CheckBulkResourcesAuthorizationResponse {
    type Raw = ResourceAuthorizationResult.Raw[];
}
