/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";

export const Group: core.serialization.ObjectSchema<serializers.Group.Raw, Credal.Group> = core.serialization.object({
    name: core.serialization.string(),
    id: core.serialization.string().optional(),
});

export declare namespace Group {
    interface Raw {
        name: string;
        id?: string | null;
    }
}
