/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";
import { Principal } from "./Principal";

export const PrincipalListPage: core.serialization.ObjectSchema<
    serializers.PrincipalListPage.Raw,
    Credal.PrincipalListPage
> = core.serialization.object({
    principals: core.serialization.list(Principal),
    nextPageToken: core.serialization.string().optional(),
});

export declare namespace PrincipalListPage {
    interface Raw {
        principals: Principal.Raw[];
        nextPageToken?: string | null;
    }
}
