/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";
import { ResourceIdentifier } from "../../common/types/ResourceIdentifier";

export const ResourceAuthorizationResult: core.serialization.ObjectSchema<
    serializers.ResourceAuthorizationResult.Raw,
    Credal.ResourceAuthorizationResult
> = core.serialization.object({
    resourceIdentifier: ResourceIdentifier,
    authorized: core.serialization.boolean(),
});

export declare namespace ResourceAuthorizationResult {
    interface Raw {
        resourceIdentifier: ResourceIdentifier.Raw;
        authorized: boolean;
    }
}
