/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";

export const User: core.serialization.ObjectSchema<serializers.User.Raw, Credal.User> = core.serialization.object({
    email: core.serialization.string(),
    name: core.serialization.string().optional(),
    id: core.serialization.string().optional(),
});

export declare namespace User {
    interface Raw {
        email: string;
        name?: string | null;
        id?: string | null;
    }
}
