// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../../../core/index.js";

export interface UploadFileRequest {
    /** The file to upload. Supported formats: PDF (.pdf), Word (.docx), Excel (.xlsx, .xls), PowerPoint (.pptx, .ppt), CSV (.csv), and text files. */
    file: core.file.Uploadable;
    /** The name of the document you want to upload. If not provided, the original filename will be used. */
    documentName?: string;
    /** [Legacy] The user on behalf of whom the document should be uploaded. In most cases, this can simply be the email of the developer making the API call. This field will be removed in the future in favor of purely specifying permissions via allowedUsersEmailAddresses. */
    uploadAsUserEmail: string;
    /** The external ID of the document. This is typically the ID as it exists in its original external system. Uploads to the same external ID will update the document in Credal. */
    documentExternalId: string;
    /** Users allowed to access the document. Can be provided as a JSON array string (e.g., ["user1@example.com","user2@example.com"]) or comma-separated list (e.g., "user1@example.com,user2@example.com"). Unlike Credal's out of the box connectors which reconcile various permissions models from 3rd party software, for custom uploads the caller is responsible for specifying who can access the document and currently flattening groups if applicable. Documents can also be marked as internal public. */
    allowedUsersEmailAddresses?: string;
    /** The external URL of the document you want to upload. If provided Credal will link to this URL. */
    documentExternalUrl?: string;
    /** Optional JSON string representing any custom metadata for this document (e.g., '{"key1":"value1","key2":"value2"}'). */
    customMetadata?: string;
    /** If specified, the document will also be added to the provided document collection. This operation is eventually consistent, meaning the document does not immediately start appearing in searches of that collection due to an asynchronous embedding process. To achieve strong consistency use the `awaitVectorStoreSync` parameter. */
    collectionId?: string;
    /** If set to "true", document contents will be re-uploaded and re-embedded even if the document already exists in Credal. */
    forceUpdate?: string;
    /** If set to "true", document will be accessible to everyone within the organization of the uploader. */
    internalPublic?: string;
    /** ISO 8601 date string indicating when the document was last updated in the source system (e.g., "2025-11-03T21:15:00Z"). */
    sourceSystemUpdated?: string;
    /** Document uploads are eventually consistent by default. If set to "true" the API will wait for the vector store to be updated before returning. This is useful if you want to ensure that the document is immediately searchable after this call returns. */
    awaitVectorStoreSync?: string;
}
