/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Credal from "../../../../../api/index";
import * as core from "../../../../../core";

export const AddCollectionToCopilotRequest: core.serialization.Schema<
    serializers.AddCollectionToCopilotRequest.Raw,
    Credal.AddCollectionToCopilotRequest
> = core.serialization.object({
    copilotId: core.serialization.string(),
    collectionId: core.serialization.string(),
});

export declare namespace AddCollectionToCopilotRequest {
    export interface Raw {
        copilotId: string;
        collectionId: string;
    }
}
