/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Credal from "../../../../../api/index";
import * as core from "../../../../../core";
import { Collaborator } from "../../../common/types/Collaborator";

export const CreateCopilotRequest: core.serialization.Schema<
    serializers.CreateCopilotRequest.Raw,
    Credal.CreateCopilotRequest
> = core.serialization.object({
    name: core.serialization.string(),
    description: core.serialization.string(),
    collaborators: core.serialization.list(Collaborator),
});

export declare namespace CreateCopilotRequest {
    export interface Raw {
        name: string;
        description: string;
        collaborators: Collaborator.Raw[];
    }
}
