/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Credal from "../../../../../api/index";
import * as core from "../../../../../core";

export const DeleteCopilotRequest: core.serialization.Schema<
    serializers.DeleteCopilotRequest.Raw,
    Credal.DeleteCopilotRequest
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace DeleteCopilotRequest {
    export interface Raw {
        id: string;
    }
}
