/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Credal from "../../../../../api/index";
import * as core from "../../../../../core";
import { InputVariable } from "../../types/InputVariable";

export const SendMessageRequest: core.serialization.Schema<
    serializers.SendMessageRequest.Raw,
    Credal.SendMessageRequest
> = core.serialization.object({
    agentId: core.serialization.string(),
    message: core.serialization.string(),
    userEmail: core.serialization.string(),
    conversationId: core.serialization.string().optional(),
    inputVariables: core.serialization.list(InputVariable).optional(),
});

export declare namespace SendMessageRequest {
    export interface Raw {
        agentId: string;
        message: string;
        userEmail: string;
        conversationId?: string | null;
        inputVariables?: InputVariable.Raw[] | null;
    }
}
