/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Credal from "../../../../../api/index";
import * as core from "../../../../../core";

export const SendMessageRequest: core.serialization.Schema<
    serializers.SendMessageRequest.Raw,
    Credal.SendMessageRequest
> = core.serialization.object({
    message: core.serialization.string(),
    userEmail: core.serialization.string(),
    conversationId: core.serialization.string().optional(),
});

export declare namespace SendMessageRequest {
    interface Raw {
        message: string;
        userEmail: string;
        conversationId?: string | null;
    }
}
