/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Credal from "../../../../../api/index";
import * as core from "../../../../../core";
import { InputVariable } from "../../types/InputVariable";

export const StreamMessageRequest: core.serialization.Schema<
    serializers.StreamMessageRequest.Raw,
    Credal.StreamMessageRequest
> = core.serialization.object({
    copilotId: core.serialization.string(),
    message: core.serialization.string(),
    email: core.serialization.string(),
    conversationId: core.serialization.string().optional(),
    inputVariables: core.serialization.list(InputVariable).optional(),
});

export declare namespace StreamMessageRequest {
    export interface Raw {
        copilotId: string;
        message: string;
        email: string;
        conversationId?: string | null;
        inputVariables?: InputVariable.Raw[] | null;
    }
}
