/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Credal from "../../../../../api/index";
import * as core from "../../../../../core";
import { Configuration } from "../../types/Configuration";

export const UpdateConfigurationRequest: core.serialization.Schema<
    serializers.UpdateConfigurationRequest.Raw,
    Credal.UpdateConfigurationRequest
> = core.serialization.object({
    copilotId: core.serialization.string(),
    configuration: Configuration,
});

export declare namespace UpdateConfigurationRequest {
    export interface Raw {
        copilotId: string;
        configuration: Configuration.Raw;
    }
}
