/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../../index.js";

/**
 * @example
 *     {
 *         mongoURI: "mongodb+srv://cluster0.hzwklqn.mongodb.net/Cluster0?retryWrites=true&w=majority",
 *         collectionId: "ac20e6ba-0bae-11ef-b25a-efca73df4c3a",
 *         config: {
 *             syncName: "My sales transcripts",
 *             collectionName: "myCollection",
 *             filterExpression: {
 *                 "status": {
 *                     "$ne": "disabled"
 *                 }
 *             },
 *             sourceFields: {
 *                 body: "body",
 *                 sourceName: "meetingName",
 *                 sourceSystemUpdated: "transcriptDatetime",
 *                 sourceUrl: "link"
 *             }
 *         }
 *     }
 */
export interface CreateMongoCollectionSyncRequest {
    collectionId: string;
    mongoURI: string;
    config: Credal.MongoCollectionSyncConfig;
}
