/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         collectionId: "82e4b12a-6990-45d4-8ebd-85c00e030c24"
 *     }
 */
export interface ListDocumentsInCollectionRequest {
    /** The ID of the document collection to list documents from. */
    collectionId: string;
}
