/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../../index";

/**
 * @example
 *     {
 *         mongoUri: "mongodb+srv://cluster0.hzwklqn.mongodb.net/Cluster0?retryWrites=true&w=majority",
 *         mongoCredentialId: "5988ed76-6ee1-11ef-97dd-1fca54b7c4bc",
 *         config: {
 *             syncName: "My recent summarized sales transcripts",
 *             collectionName: "myCollection",
 *             filterExpression: {
 *                 "transcriptDatetime": {
 *                     "$gt": "2023-01-01T00:00:00.000Z"
 *                 }
 *             },
 *             sourceFields: {
 *                 body: "transcriptSummary",
 *                 sourceName: "meetingName",
 *                 sourceSystemUpdated: "transcriptDatetime",
 *                 sourceUrl: "link"
 *             }
 *         }
 *     }
 */
export interface UpdateMongoCollectionSyncRequest {
    mongoCredentialId: string;
    mongoUri: string;
    config: Credal.MongoCollectionSyncConfig;
}
