/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Credal from "../../../../../api/index";
import * as core from "../../../../../core";
import { HumanConfirmationChannel } from "../../types/HumanConfirmationChannel";

export const InvokeActionRequest: core.serialization.Schema<
    serializers.InvokeActionRequest.Raw,
    Credal.InvokeActionRequest
> = core.serialization.object({
    actionId: core.serialization.string(),
    actionInputs: core.serialization.unknown(),
    userEmail: core.serialization.string(),
    requireHumanConfirmation: core.serialization.boolean(),
    humanConfirmationChannel: HumanConfirmationChannel.optional(),
    justification: core.serialization.string(),
    auditLogId: core.serialization.string(),
});

export declare namespace InvokeActionRequest {
    interface Raw {
        actionId: string;
        actionInputs?: unknown;
        userEmail: string;
        requireHumanConfirmation: boolean;
        humanConfirmationChannel?: HumanConfirmationChannel.Raw | null;
        justification: string;
        auditLogId: string;
    }
}
