/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         userEmail: "ravin@credal.ai"
 *     }
 */
export interface CreateConversationRequest {
    /**
     * End-user for the conversation.
     *
     */
    userEmail: string;
}
