/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         id: "ac20e6ba-0bae-11ef-b25a-efca73df4c3a"
 *     }
 */
export interface DeleteCopilotRequest {
    /** Copilot ID */
    id: string;
}
