/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../../index";

/**
 * @example
 *     {
 *         userEmail: "ravin@credal.ai",
 *         messageId: "dd721cd8-4bf2-4b94-9869-258df3dab9dc",
 *         agentId: "82e4b12a-6990-45d4-8ebd-85c00e030c24",
 *         messageFeedback: {
 *             feedback: "NEGATIVE",
 *             suggestedAnswer: "Yes, Credal is SOC 2 compliant.",
 *             descriptiveFeedback: "The response should be extremely clear and concise."
 *         }
 *     }
 */
export interface ProvideMessageFeedbackRequest {
    /** Credal-generated Agent ID to specify which agent to route the request to. */
    agentId: string;
    /** The user profile you want to use when providing feedback. */
    userEmail: string;
    /** The message ID for which feedback is being provided. */
    messageId: string;
    /** The feedback provided by the user. */
    messageFeedback: Credal.MessageFeedback;
}
