/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../../index";

/**
 * @example
 *     {
 *         userEmail: "ravin@credal.ai",
 *         messageId: "dd721cd8-4bf2-4b94-9869-258df3dab9dc",
 *         messageFeedback: {
 *             feedback: Credal.FeedbackEnum.Negative,
 *             suggestedAnswer: "Yes, Credal is SOC 2 compliant."
 *         }
 *     }
 */
export interface ProvideMessageFeedbackRequest {
    /**
     * The user profile you want to use when providing feedback.
     *
     */
    userEmail: string;
    /**
     * The message ID for which feedback is being provided.
     *
     */
    messageId: string;
    /**
     * The feedback provided by the user.
     *
     */
    messageFeedback: Credal.MessageFeedback;
}
