/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../../index";

/**
 * @example
 *     {
 *         copilotId: "82e4b12a-6990-45d4-8ebd-85c00e030c24",
 *         configuration: {
 *             name: "Customer Agent",
 *             description: "This agent is used to answer customer requests based on internal documentation.",
 *             prompt: "You are a polite, helpful assistant used to answer customer requests.",
 *             aiEndpointConfiguration: {
 *                 baseUrl: "https://api.openai.com/v1/",
 *                 apiKey: "<YOUR_API_KEY_HERE>"
 *             }
 *         }
 *     }
 */
export interface UpdateConfigurationRequest {
    /** Credal-generated agent ID to add the collection to. */
    copilotId: string;
    configuration: Credal.Configuration;
}
