/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";
import { PolicyTrigger } from "./PolicyTrigger";

export const BlockedChunk: core.serialization.ObjectSchema<serializers.BlockedChunk.Raw, Credal.BlockedChunk> =
    core.serialization.object({
        conversationId: core.serialization.string(),
        warnings: core.serialization.list(core.serialization.string()),
        blocks: core.serialization.list(core.serialization.string()),
        policyTriggers: core.serialization.list(PolicyTrigger),
    });

export declare namespace BlockedChunk {
    export interface Raw {
        conversationId: string;
        warnings: string[];
        blocks: string[];
        policyTriggers: PolicyTrigger.Raw[];
    }
}
