/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";
import { Filter } from "./Filter";

export const CollectionFilteredData: core.serialization.ObjectSchema<
    serializers.CollectionFilteredData.Raw,
    Credal.CollectionFilteredData
> = core.serialization.object({
    collectionId: core.serialization.string(),
    filteredDataIds: core.serialization.list(core.serialization.string()),
    filters: core.serialization.list(Filter),
});

export declare namespace CollectionFilteredData {
    export interface Raw {
        collectionId: string;
        filteredDataIds: string[];
        filters: Filter.Raw[];
    }
}
