/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";
import { AiEndpointConfiguration } from "./AiEndpointConfiguration";

export const Configuration: core.serialization.ObjectSchema<serializers.Configuration.Raw, Credal.Configuration> =
    core.serialization.object({
        aiEndpointConfiguration: AiEndpointConfiguration.optional(),
        name: core.serialization.string().optional(),
        description: core.serialization.string().optional(),
        prompt: core.serialization.string().optional(),
    });

export declare namespace Configuration {
    export interface Raw {
        aiEndpointConfiguration?: AiEndpointConfiguration.Raw | null;
        name?: string | null;
        description?: string | null;
        prompt?: string | null;
    }
}
