/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";

export const CreateConversationResponse: core.serialization.ObjectSchema<
    serializers.CreateConversationResponse.Raw,
    Credal.CreateConversationResponse
> = core.serialization.object({
    conversationId: core.serialization.string(),
});

export declare namespace CreateConversationResponse {
    export interface Raw {
        conversationId: string;
    }
}
