/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";

export const CreateCopilotResponse: core.serialization.ObjectSchema<
    serializers.CreateCopilotResponse.Raw,
    Credal.CreateCopilotResponse
> = core.serialization.object({
    agentId: core.serialization.string(),
});

export declare namespace CreateCopilotResponse {
    export interface Raw {
        agentId: string;
    }
}
