/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";

export const DataChunk: core.serialization.ObjectSchema<serializers.DataChunk.Raw, Credal.DataChunk> =
    core.serialization.object({
        chunk: core.serialization.string(),
    });

export declare namespace DataChunk {
    interface Raw {
        chunk: string;
    }
}
