/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";

export const EndOfMessageChunk: core.serialization.ObjectSchema<
    serializers.EndOfMessageChunk.Raw,
    Credal.EndOfMessageChunk
> = core.serialization.object({});

export declare namespace EndOfMessageChunk {
    export interface Raw {}
}
