/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";

export const FeedbackEnum: core.serialization.Schema<serializers.FeedbackEnum.Raw, Credal.FeedbackEnum> =
    core.serialization.enum_(["POSITIVE", "NEGATIVE"]);

export declare namespace FeedbackEnum {
    export type Raw = "POSITIVE" | "NEGATIVE";
}
