/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";
import { WebSearchResult } from "./WebSearchResult";
import { DataFilter } from "./DataFilter";

export const InitialChunk: core.serialization.ObjectSchema<serializers.InitialChunk.Raw, Credal.InitialChunk> =
    core.serialization.object({
        conversationId: core.serialization.string(),
        warnings: core.serialization.list(core.serialization.string()),
        webSearchResults: core.serialization.list(WebSearchResult),
        dataFilters: DataFilter.optional(),
    });

export declare namespace InitialChunk {
    export interface Raw {
        conversationId: string;
        warnings: string[];
        webSearchResults: WebSearchResult.Raw[];
        dataFilters?: DataFilter.Raw | null;
    }
}
