/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";

export const InputVariable: core.serialization.ObjectSchema<serializers.InputVariable.Raw, Credal.InputVariable> =
    core.serialization.object({
        name: core.serialization.string(),
        urls: core.serialization.list(core.serialization.string()),
    });

export declare namespace InputVariable {
    interface Raw {
        name: string;
        urls: string[];
    }
}
