/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";

export const InsertedAuditLog: core.serialization.ObjectSchema<
    serializers.InsertedAuditLog.Raw,
    Credal.InsertedAuditLog
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace InsertedAuditLog {
    export interface Raw {
        id: string;
    }
}
