/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";

export const PolicyTrigger: core.serialization.ObjectSchema<serializers.PolicyTrigger.Raw, Credal.PolicyTrigger> =
    core.serialization.object({
        id: core.serialization.string(),
        name: core.serialization.string(),
        description: core.serialization.string(),
    });

export declare namespace PolicyTrigger {
    interface Raw {
        id: string;
        name: string;
        description: string;
    }
}
