/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";
import { ExternalResourceId } from "../../common/types/ExternalResourceId";

export const ReferencedSource: core.serialization.ObjectSchema<
    serializers.ReferencedSource.Raw,
    Credal.ReferencedSource
> = core.serialization.object({
    id: core.serialization.string(),
    externalResourceId: ExternalResourceId,
    name: core.serialization.string(),
    url: core.serialization.string().optional(),
});

export declare namespace ReferencedSource {
    export interface Raw {
        id: string;
        externalResourceId: ExternalResourceId.Raw;
        name: string;
        url?: string | null;
    }
}
