/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";

export const ResponseChunk: core.serialization.ObjectSchema<serializers.ResponseChunk.Raw, Credal.ResponseChunk> =
    core.serialization.object({
        message: core.serialization.string(),
        dataChunk: core.serialization.string(),
    });

export declare namespace ResponseChunk {
    interface Raw {
        message: string;
        dataChunk: string;
    }
}
