/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";
import { InitialChunk } from "./InitialChunk";
import { DataChunk } from "./DataChunk";
import { FinalChunk } from "./FinalChunk";
import { BlockedChunk } from "./BlockedChunk";

export const StreamingChunk: core.serialization.Schema<serializers.StreamingChunk.Raw, Credal.StreamingChunk> =
    core.serialization.undiscriminatedUnion([InitialChunk, DataChunk, FinalChunk, BlockedChunk]);

export declare namespace StreamingChunk {
    type Raw = InitialChunk.Raw | DataChunk.Raw | FinalChunk.Raw | BlockedChunk.Raw;
}
