/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";
import { Operator } from "../../common/types/Operator";

export const StringFieldSchema: core.serialization.ObjectSchema<
    serializers.StringFieldSchema.Raw,
    Credal.StringFieldSchema
> = core.serialization.object({
    field: core.serialization.string(),
    operator: Operator,
    value: core.serialization.string(),
});

export declare namespace StringFieldSchema {
    export interface Raw {
        field: string;
        operator: Operator.Raw;
        value: string;
    }
}
