/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ActionStatus =
    | "PENDING_APPROVAL"
    | "IN_PROGRESS"
    | "APPROVED_SUCCEEDED"
    | "APPROVED_FAILED"
    | "NO_APPROVAL_NEEDED_SUCCEEDED"
    | "NO_APPROVAL_NEEDED_FAILED";

export const ActionStatus = {
    PendingApproval: "PENDING_APPROVAL",
    InProgress: "IN_PROGRESS",
    ApprovedSucceeded: "APPROVED_SUCCEEDED",
    ApprovedFailed: "APPROVED_FAILED",
    NoApprovalNeededSucceeded: "NO_APPROVAL_NEEDED_SUCCEEDED",
    NoApprovalNeededFailed: "NO_APPROVAL_NEEDED_FAILED",
} as const;
