/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../index";

export type HumanConfirmationChannel =
    | Credal.HumanConfirmationChannel.DirectMessage
    | Credal.HumanConfirmationChannel.SlackThread
    | Credal.HumanConfirmationChannel.Conversation;

export declare namespace HumanConfirmationChannel {
    interface DirectMessage extends Credal.DirectMessage {
        type: "directMessage";
    }

    interface SlackThread extends Credal.SlackThread {
        type: "slackThread";
    }

    interface Conversation extends Credal.Conversation {
        type: "conversation";
    }
}
