/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Credal from "../../../../../api/index";
import * as core from "../../../../../core";
import { ResourceIdentifier } from "../../../common/types/ResourceIdentifier";

export const AddDocumentsToCollectionRequest: core.serialization.Schema<
    serializers.AddDocumentsToCollectionRequest.Raw,
    Credal.AddDocumentsToCollectionRequest
> = core.serialization.object({
    collectionId: core.serialization.string(),
    resourceIdentifiers: core.serialization.list(ResourceIdentifier),
});

export declare namespace AddDocumentsToCollectionRequest {
    export interface Raw {
        collectionId: string;
        resourceIdentifiers: ResourceIdentifier.Raw[];
    }
}
