/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Credal from "../../../../../api/index";
import * as core from "../../../../../core";
import { MongoCollectionSyncConfig } from "../../types/MongoCollectionSyncConfig";

export const CreateMongoCollectionSyncRequest: core.serialization.Schema<
    serializers.CreateMongoCollectionSyncRequest.Raw,
    Credal.CreateMongoCollectionSyncRequest
> = core.serialization.object({
    collectionId: core.serialization.string(),
    mongoUri: core.serialization.property("mongoURI", core.serialization.string()),
    config: MongoCollectionSyncConfig,
});

export declare namespace CreateMongoCollectionSyncRequest {
    interface Raw {
        collectionId: string;
        mongoURI: string;
        config: MongoCollectionSyncConfig.Raw;
    }
}
