/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Credal from "../../../../../api/index";
import * as core from "../../../../../core";

export const DeleteCollectionRequest: core.serialization.Schema<
    serializers.DeleteCollectionRequest.Raw,
    Credal.DeleteCollectionRequest
> = core.serialization.object({
    collectionId: core.serialization.string(),
});

export declare namespace DeleteCollectionRequest {
    interface Raw {
        collectionId: string;
    }
}
