// This file was auto-generated by Fern from our API Definition.

import { CredalClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SearchClient", () => {
    test("searchDocumentCollection", async () => {
        const server = mockServerPool.createServer();
        const client = new CredalClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            collectionId: "82e4b12a-6990-45d4-8ebd-85c00e030c24",
            searchQuery: "ABC Corp",
            structuredQueryFilters: [{ field: "status", operator: "==", value: "Open" }],
            userEmail: "jack@credal.ai",
            searchOptions: {
                maxChunks: 10,
                mergeContents: true,
                threshold: 0.8,
                enableSmartFiltering: true,
                enableQueryExtraction: true,
                enableReranking: true,
            },
        };
        const rawResponseBody = {
            searchId: "76b534be-5d5c-11ee-b268-87f1fd934c81",
            searchTermsUsed: ["ABC Corp"],
            structuredFiltersApplied: [{ field: "status", operator: "==", value: "Open" }],
            results: [
                {
                    documentId: "82e4b12a-6990-45d4-8ebd-85c00e030c24",
                    documentName: "ABC Corp - Initial meeting transcript",
                    documentUrl: "https://docs.google.com/document/d/1PNiSvrRKyO4Yfv1IMnPkI1JTZr-762Rd7pRdygBi0eE/edit",
                    documentExternalId: "1PNiSvrRKyO4Yfv1IMnPkI1JTZr-762Rd7pRdygBi0eE",
                    documentMetadata: { customerName: "ABC Corp", meetingDate: "2021-01-01T00:00:00Z" },
                    chunks: [
                        {
                            chunkId: "8d49fa7e-f09a-4bd4-ae94-4c089c9043a0",
                            chunkIndex: 0,
                            text: "The cat sat on the mat.",
                            score: 0.9,
                        },
                        {
                            chunkId: "c24f99f9-2477-461b-8f8f-90a82a40879d",
                            chunkIndex: 1,
                            text: "The quick brown fox jumps over the lazy dog.",
                            score: 0.8,
                        },
                        {
                            chunkId: "6413d18c-b37f-4985-9045-cc8d6e100a17",
                            chunkIndex: 2,
                            text: "The lazy dog lazed.",
                            score: 0.7,
                        },
                    ],
                    mergedContents:
                        "The cat sat on the mat. The quick brown fox jumps over the lazy dog. The lazy dog lazed.",
                },
                {
                    documentId: "90998ceb-1c10-4d2a-96cb-acf89fa3005e",
                    documentName: "XYZ Corp - Follow-up transcript",
                    documentUrl:
                        "https://credalai-my.sharepoint.com/:w:/g/credalai_onmicrosoft_com/ESb7bpzm2FdGqPTlXsQW2P4BpBhsrZuKS_PgJlaoJffo9A?e=Ecv5j1",
                    documentExternalId: "ESb7bpzm2FdGqPTlXsQW2P4BpBhsrZuKS_PgJlaoJffo9A",
                    documentMetadata: { customerName: "XYZ Corp", meetingDate: "2021-01-02T00:00:00Z" },
                    chunks: [
                        {
                            chunkId: "3664912a-3edb-4d88-b624-80db99d383e6",
                            chunkIndex: 0,
                            text: "The cat sat on the mat.",
                            score: 0.7,
                        },
                        {
                            chunkId: "da9d43a4-2927-442c-8e5c-b9ef86f56fc3",
                            chunkIndex: 1,
                            text: "The quick brown fox jumps over the lazy dog.",
                            score: 0.9,
                        },
                        {
                            chunkId: "8d882e9f-8eda-479b-ae2a-359ebae7b626",
                            chunkIndex: 2,
                            text: "The lazy dog lazed.",
                            score: 0.75,
                        },
                    ],
                    mergedContents:
                        "The cat sat on the mat. The quick brown fox jumps over the lazy dog. The lazy dog lazed.",
                },
            ],
        };
        server
            .mockEndpoint()
            .post("/v0/search/searchDocumentCollection")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.search.searchDocumentCollection({
            collectionId: "82e4b12a-6990-45d4-8ebd-85c00e030c24",
            searchQuery: "ABC Corp",
            structuredQueryFilters: [
                {
                    field: "status",
                    operator: "==",
                    value: "Open",
                },
            ],
            userEmail: "jack@credal.ai",
            searchOptions: {
                maxChunks: 10,
                mergeContents: true,
                threshold: 0.8,
                enableSmartFiltering: true,
                enableQueryExtraction: true,
                enableReranking: true,
            },
        });
        expect(response).toEqual({
            searchId: "76b534be-5d5c-11ee-b268-87f1fd934c81",
            searchTermsUsed: ["ABC Corp"],
            structuredFiltersApplied: [
                {
                    field: "status",
                    operator: "==",
                    value: "Open",
                },
            ],
            results: [
                {
                    documentId: "82e4b12a-6990-45d4-8ebd-85c00e030c24",
                    documentName: "ABC Corp - Initial meeting transcript",
                    documentUrl: "https://docs.google.com/document/d/1PNiSvrRKyO4Yfv1IMnPkI1JTZr-762Rd7pRdygBi0eE/edit",
                    documentExternalId: "1PNiSvrRKyO4Yfv1IMnPkI1JTZr-762Rd7pRdygBi0eE",
                    documentMetadata: {
                        customerName: "ABC Corp",
                        meetingDate: "2021-01-01T00:00:00Z",
                    },
                    chunks: [
                        {
                            chunkId: "8d49fa7e-f09a-4bd4-ae94-4c089c9043a0",
                            chunkIndex: 0,
                            text: "The cat sat on the mat.",
                            score: 0.9,
                        },
                        {
                            chunkId: "c24f99f9-2477-461b-8f8f-90a82a40879d",
                            chunkIndex: 1,
                            text: "The quick brown fox jumps over the lazy dog.",
                            score: 0.8,
                        },
                        {
                            chunkId: "6413d18c-b37f-4985-9045-cc8d6e100a17",
                            chunkIndex: 2,
                            text: "The lazy dog lazed.",
                            score: 0.7,
                        },
                    ],
                    mergedContents:
                        "The cat sat on the mat. The quick brown fox jumps over the lazy dog. The lazy dog lazed.",
                },
                {
                    documentId: "90998ceb-1c10-4d2a-96cb-acf89fa3005e",
                    documentName: "XYZ Corp - Follow-up transcript",
                    documentUrl:
                        "https://credalai-my.sharepoint.com/:w:/g/credalai_onmicrosoft_com/ESb7bpzm2FdGqPTlXsQW2P4BpBhsrZuKS_PgJlaoJffo9A?e=Ecv5j1",
                    documentExternalId: "ESb7bpzm2FdGqPTlXsQW2P4BpBhsrZuKS_PgJlaoJffo9A",
                    documentMetadata: {
                        customerName: "XYZ Corp",
                        meetingDate: "2021-01-02T00:00:00Z",
                    },
                    chunks: [
                        {
                            chunkId: "3664912a-3edb-4d88-b624-80db99d383e6",
                            chunkIndex: 0,
                            text: "The cat sat on the mat.",
                            score: 0.7,
                        },
                        {
                            chunkId: "da9d43a4-2927-442c-8e5c-b9ef86f56fc3",
                            chunkIndex: 1,
                            text: "The quick brown fox jumps over the lazy dog.",
                            score: 0.9,
                        },
                        {
                            chunkId: "8d882e9f-8eda-479b-ae2a-359ebae7b626",
                            chunkIndex: 2,
                            text: "The lazy dog lazed.",
                            score: 0.75,
                        },
                    ],
                    mergedContents:
                        "The cat sat on the mat. The quick brown fox jumps over the lazy dog. The lazy dog lazed.",
                },
            ],
        });
    });
});
