/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";

export const DocumentCollectionSearchOptions: core.serialization.ObjectSchema<
    serializers.DocumentCollectionSearchOptions.Raw,
    Credal.DocumentCollectionSearchOptions
> = core.serialization.object({
    maxChunks: core.serialization.number().optional(),
    mergeContents: core.serialization.boolean().optional(),
    threshold: core.serialization.number().optional(),
    enableSmartFiltering: core.serialization.boolean().optional(),
    enableQueryExtraction: core.serialization.boolean().optional(),
    enableReranking: core.serialization.boolean().optional(),
});

export declare namespace DocumentCollectionSearchOptions {
    export interface Raw {
        maxChunks?: number | null;
        mergeContents?: boolean | null;
        threshold?: number | null;
        enableSmartFiltering?: boolean | null;
        enableQueryExtraction?: boolean | null;
        enableReranking?: boolean | null;
    }
}
