/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";

export const Operator: core.serialization.Schema<serializers.Operator.Raw, Credal.Operator> = core.serialization.enum_([
    "<",
    ">",
    "<=",
    ">=",
    "!=",
    "==",
    "contains",
]);

export declare namespace Operator {
    type Raw = "<" | ">" | "<=" | ">=" | "!=" | "==" | "contains";
}
