/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";
import { SingleFieldFilter } from "./SingleFieldFilter";
import { DocumentCollectionSearchResult } from "./DocumentCollectionSearchResult";

export const SearchDocumentCollectionResponse: core.serialization.ObjectSchema<
    serializers.SearchDocumentCollectionResponse.Raw,
    Credal.SearchDocumentCollectionResponse
> = core.serialization.object({
    searchTermsUsed: core.serialization.list(core.serialization.string()),
    structuredFiltersApplied: core.serialization.list(SingleFieldFilter),
    searchId: core.serialization.string(),
    results: core.serialization.list(DocumentCollectionSearchResult),
});

export declare namespace SearchDocumentCollectionResponse {
    export interface Raw {
        searchTermsUsed: string[];
        structuredFiltersApplied: SingleFieldFilter.Raw[];
        searchId: string;
        results: DocumentCollectionSearchResult.Raw[];
    }
}
