/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";

export const SearchResultChunk: core.serialization.ObjectSchema<
    serializers.SearchResultChunk.Raw,
    Credal.SearchResultChunk
> = core.serialization.object({
    chunkId: core.serialization.string(),
    chunkIndex: core.serialization.number(),
    text: core.serialization.string(),
    score: core.serialization.number(),
});

export declare namespace SearchResultChunk {
    export interface Raw {
        chunkId: string;
        chunkIndex: number;
        text: string;
        score: number;
    }
}
