// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import * as core from "./core/index.js";
import { mergeHeaders } from "./core/headers.js";
import * as environments from "./environments.js";
import { Copilots } from "./api/resources/copilots/client/Client.js";
import { DocumentCatalog } from "./api/resources/documentCatalog/client/Client.js";
import { DocumentCollections } from "./api/resources/documentCollections/client/Client.js";
import { Search } from "./api/resources/search/client/Client.js";
import { Users } from "./api/resources/users/client/Client.js";

export declare namespace CredalClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class CredalClient {
    protected readonly _options: CredalClient.Options;
    protected _copilots: Copilots | undefined;
    protected _documentCatalog: DocumentCatalog | undefined;
    protected _documentCollections: DocumentCollections | undefined;
    protected _search: Search | undefined;
    protected _users: Users | undefined;

    constructor(_options: CredalClient.Options = {}) {
        this._options = {
            ..._options,
            headers: mergeHeaders(
                {
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-SDK-Name": "@credal/sdk",
                    "X-Fern-SDK-Version": "0.1.8",
                    "User-Agent": "@credal/sdk/0.1.8",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get copilots(): Copilots {
        return (this._copilots ??= new Copilots(this._options));
    }

    public get documentCatalog(): DocumentCatalog {
        return (this._documentCatalog ??= new DocumentCatalog(this._options));
    }

    public get documentCollections(): DocumentCollections {
        return (this._documentCollections ??= new DocumentCollections(this._options));
    }

    public get search(): Search {
        return (this._search ??= new Search(this._options));
    }

    public get users(): Users {
        return (this._users ??= new Users(this._options));
    }
}
