// This file was auto-generated by Fern from our API Definition.

import { CopilotsClient } from "./api/resources/copilots/client/Client.js";
import { DocumentCatalogClient } from "./api/resources/documentCatalog/client/Client.js";
import { DocumentCollectionsClient } from "./api/resources/documentCollections/client/Client.js";
import { SearchClient } from "./api/resources/search/client/Client.js";
import { UsersClient } from "./api/resources/users/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { normalizeClientOptions } from "./BaseClient.js";

export declare namespace CredalClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class CredalClient {
    protected readonly _options: CredalClient.Options;
    protected _copilots: CopilotsClient | undefined;
    protected _documentCatalog: DocumentCatalogClient | undefined;
    protected _documentCollections: DocumentCollectionsClient | undefined;
    protected _search: SearchClient | undefined;
    protected _users: UsersClient | undefined;

    constructor(options: CredalClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    public get copilots(): CopilotsClient {
        return (this._copilots ??= new CopilotsClient(this._options));
    }

    public get documentCatalog(): DocumentCatalogClient {
        return (this._documentCatalog ??= new DocumentCatalogClient(this._options));
    }

    public get documentCollections(): DocumentCollectionsClient {
        return (this._documentCollections ??= new DocumentCollectionsClient(this._options));
    }

    public get search(): SearchClient {
        return (this._search ??= new SearchClient(this._options));
    }

    public get users(): UsersClient {
        return (this._users ??= new UsersClient(this._options));
    }
}
