/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const CredalEnvironment = {
    Production: "https://api.credal.ai/api",
} as const;

export type CredalEnvironment = typeof CredalEnvironment.Production;
