/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../index.js";

export interface ListDocumentsInCollectionResponse {
    resourceIdentifiers: Credal.ResourceIdentifier[];
}
