// This file was auto-generated by Fern from our API Definition.

export interface MongoSourceFieldsConfig {
    body: string;
    sourceName: string;
    sourceSystemUpdated?: string;
    sourceUrl?: string;
}
