/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../index";

export interface CollectionFilteredData {
    collectionId: string;
    filteredDataIds: string[];
    filters: Credal.Filter[];
}
