// This file was auto-generated by Fern from our API Definition.

import type * as Credal from "../../../index.js";

export interface CollectionFilteredData {
    collectionId: string;
    filteredDataIds: string[];
    filters: Credal.Filter[];
}
