/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../index";

export interface Configuration {
    aiEndpointConfiguration?: Credal.AiEndpointConfiguration;
    name?: string;
    description?: string;
    prompt?: string;
}
