// This file was auto-generated by Fern from our API Definition.

import type * as Credal from "../../../index.js";

export interface Configuration {
    aiEndpointConfiguration?: Credal.AiEndpointConfiguration;
    name?: string;
    description?: string;
    prompt?: string;
}
