/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../index";

export interface DataFilter {
    semanticSearchTerms: string[];
    webSearchTerm: string[];
    filteredDataSourcesPerCollection: Credal.CollectionFilteredData[];
}
