// This file was auto-generated by Fern from our API Definition.

import type * as Credal from "../../../index.js";

export interface DataFilter {
    semanticSearchTerms: string[];
    webSearchTerm: string[];
    filteredDataSourcesPerCollection: Credal.CollectionFilteredData[];
}
