/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../index.js";

export interface DatetimeFieldSchema {
    field: string;
    operator: Credal.Operator;
    value: string;
}
