// This file was auto-generated by Fern from our API Definition.

export interface ExportedCopilot {
    /** The unique identifier of the copilot. */
    id: string;
    /** The name of the deployed copilot version. */
    name: string;
    /** The description of the deployed copilot version. */
    description: string;
    /** Model configuration including provider, model name, temperature, and other settings. */
    modelConfiguration?: unknown;
    /** AI endpoint configuration including base URL and authentication details. */
    aiEndpointConfiguration?: unknown;
    /** List of tool configurations available to the copilot. */
    toolConfigurations?: unknown;
    /** Input variable configurations for the copilot. */
    inputs?: unknown;
    /** Deployment settings and configuration. */
    deploymentConfiguration?: unknown;
    /** ISO 8601 timestamp when the copilot was originally created. */
    agentCreatedDatetime: string;
    /** ISO 8601 timestamp when the deployed version was created. */
    versionCreatedDatetime: string;
    /** Indicates if the copilot is currently deployed (always true for export results). */
    isDeployed: boolean;
}
