// This file was auto-generated by Fern from our API Definition.

import type * as Credal from "../../../index.js";

export interface ExportCopilotsResponse {
    /** List of exported copilots matching the query filters. */
    data: Credal.ExportedCopilot[];
    /** Indicates whether there are more results available for pagination. */
    hasMore: boolean;
    /** Cursor to use for fetching the next page of results. This is a UUID string. If null or not present, there are no more results. */
    nextCursor?: string;
}
