// This file was auto-generated by Fern from our API Definition.

export const FeedbackEnum = {
    Positive: "POSITIVE",
    Negative: "NEGATIVE",
} as const;
export type FeedbackEnum = (typeof FeedbackEnum)[keyof typeof FeedbackEnum];
