/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FeedbackEnum = "POSITIVE" | "NEGATIVE";

export const FeedbackEnum = {
    Positive: "POSITIVE",
    Negative: "NEGATIVE",
} as const;
