/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../index";

export type Filter = Credal.Filter.String | Credal.Filter.Number | Credal.Filter.Boolean | Credal.Filter.Datetime;

export declare namespace Filter {
    interface String extends Credal.StringFieldSchema {
        fieldType: "string";
    }

    interface Number extends Credal.NumberFieldSchema {
        fieldType: "number";
    }

    interface Boolean extends Credal.BooleanFieldSchema {
        fieldType: "boolean";
    }

    interface Datetime extends Credal.DatetimeFieldSchema {
        fieldType: "datetime";
    }
}
