/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../index.js";

export type Filter = Credal.Filter.String | Credal.Filter.Number | Credal.Filter.Boolean | Credal.Filter.Datetime;

export namespace Filter {
    export interface String extends Credal.StringFieldSchema {
        fieldType: "string";
    }

    export interface Number extends Credal.NumberFieldSchema {
        fieldType: "number";
    }

    export interface Boolean extends Credal.BooleanFieldSchema {
        fieldType: "boolean";
    }

    export interface Datetime extends Credal.DatetimeFieldSchema {
        fieldType: "datetime";
    }
}
