// This file was auto-generated by Fern from our API Definition.

import type * as Credal from "../../../index.js";

export interface InitialChunk {
    conversationId: string;
    warnings: string[];
    webSearchResults: Credal.WebSearchResult[];
    dataFilters?: Credal.DataFilter;
}
