/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../index.js";

export interface MessageBlocked {
    policy_triggers: Credal.PolicyTrigger[];
    conversationId: string;
    blocks: string[];
    warnings: string[];
    inserted_audit_log: Credal.InsertedAuditLog;
}
