/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../index.js";

export interface MessageReply {
    policy_triggers: Credal.PolicyTrigger[];
    conversationId: string;
    response: Credal.ResponseChunk;
    warnings: string[];
    inserted_audit_log: Credal.InsertedAuditLog;
    referencedSources: Credal.ReferencedSource[];
    sourcesInDataContext: Credal.ReferencedSource[];
    webSearchResults: Credal.WebSearchResult[];
    messageId: string;
}
