/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../index";

export interface MessageFeedback {
    feedback: Credal.FeedbackEnum;
    suggestedAnswer?: string;
    descriptiveFeedback?: string;
}
