/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../index";

export interface MessageBlocked {
    policyTriggers: Credal.PolicyTrigger[];
    conversationId: string;
    blocks: string[];
    warnings: string[];
    insertedAuditLog: Credal.InsertedAuditLog;
}
