// This file was auto-generated by Fern from our API Definition.

import type * as Credal from "../../../index.js";

export interface NumberFieldSchema {
    field: string;
    operator: Credal.Operator;
    value: number;
}
