/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../index";

export interface ReferencedSource {
    id: string;
    externalResourceId: Credal.ExternalResourceId;
    name: string;
    url?: string;
}
