// This file was auto-generated by Fern from our API Definition.

import type * as Credal from "../../../index.js";

export interface SendAgentMessageResponse {
    sendChatResult: Credal.SendMessageResponse;
}
