// This file was auto-generated by Fern from our API Definition.

import type * as Credal from "../../../index.js";

export type SendMessageResponse =
    /**
     * Returned when there is a reply
     * fetched from the agent. */
    | Credal.SendMessageResponse.AiResponseResult
    /**
     * Returned when Credal detects possible
     * infosec violations and blocks the message. */
    | Credal.SendMessageResponse.BlockedResult;

export namespace SendMessageResponse {
    export interface AiResponseResult extends Credal.MessageReply {
        type: "ai_response_result";
    }

    export interface BlockedResult extends Credal.MessageBlocked {
        type: "blocked_result";
    }
}
