/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../index";

export type SendMessageResponse =
    /**
     * Returned when there is a reply
     * fetched from the copilot. */
    | Credal.SendMessageResponse.AiResponseResult
    /**
     * Returned when Credal detects possible
     * infosec violations and blocks the message. */
    | Credal.SendMessageResponse.BlockedResult;

export declare namespace SendMessageResponse {
    interface AiResponseResult extends Credal.MessageReply {
        type: "ai_response_result";
    }

    interface BlockedResult extends Credal.MessageBlocked {
        type: "blocked_result";
    }
}
