/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../index";

export type StreamingChunk =
    | Credal.StreamingChunk.Initial
    | Credal.StreamingChunk.DataChunk
    | Credal.StreamingChunk.EndOfMessage
    | Credal.StreamingChunk.FinalChunk
    | Credal.StreamingChunk.Blocked
    | Credal.StreamingChunk.ErrorChunk;

export namespace StreamingChunk {
    export interface Initial extends Credal.InitialChunk {
        event: "initial";
    }

    export interface DataChunk extends Credal.DataChunk {
        event: "data_chunk";
    }

    export interface EndOfMessage extends Credal.EndOfMessageChunk {
        event: "end_of_message";
    }

    export interface FinalChunk extends Credal.FinalChunk {
        event: "final_chunk";
    }

    export interface Blocked extends Credal.BlockedChunk {
        event: "blocked";
    }

    export interface ErrorChunk extends Credal.ErrorChunk {
        event: "error_chunk";
    }
}
