/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../index";

export type StreamingChunk =
    | Credal.StreamingChunk.Initial
    | Credal.StreamingChunk.DataChunk
    | Credal.StreamingChunk.EndOfMessage
    | Credal.StreamingChunk.FinalChunk
    | Credal.StreamingChunk.Blocked
    | Credal.StreamingChunk.ErrorChunk;

export declare namespace StreamingChunk {
    interface Initial extends Credal.InitialChunk {
        event: "initial";
    }

    interface DataChunk extends Credal.DataChunk {
        event: "data_chunk";
    }

    interface EndOfMessage extends Credal.EndOfMessageChunk {
        event: "end_of_message";
    }

    interface FinalChunk extends Credal.FinalChunk {
        event: "final_chunk";
    }

    interface Blocked extends Credal.BlockedChunk {
        event: "blocked";
    }

    interface ErrorChunk extends Credal.ErrorChunk {
        event: "error_chunk";
    }
}
