/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Credal from "../../../index";

export type StreamingChunk = Credal.InitialChunk | Credal.DataChunk | Credal.FinalChunk | Credal.BlockedChunk;
