/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";

export const ResourceType: core.serialization.Schema<serializers.ResourceType.Raw, Credal.ResourceType> =
    core.serialization.enum_([
        "GOOGLE_DRIVE_ITEM",
        "MICROSOFT_DRIVE_ITEM",
        "ZENDESK_TICKET",
        "ZENDESK_ARTICLE",
        "ZENDESK_GROUP",
        "ZENDESK_ARTICLE_SECTION",
        "ZENDESK_ARTICLE_CATEGORY",
        "CONFLUENCE_PAGE",
        "CONFLUENCE_SPACE",
        "JIRA_TICKET",
        "JIRA_PROJECT",
        "SALESFORCE_TASK",
        "BOX_FILE",
        "BOX_FOLDER",
        "NOTION_PAGE",
        "NOTION_DATABASE",
        "SLACK_CHANNEL",
        "MONGO_COLLECTION_SYNC",
        "UNKNOWN",
    ]);

export declare namespace ResourceType {
    export type Raw =
        | "GOOGLE_DRIVE_ITEM"
        | "MICROSOFT_DRIVE_ITEM"
        | "ZENDESK_TICKET"
        | "ZENDESK_ARTICLE"
        | "ZENDESK_GROUP"
        | "ZENDESK_ARTICLE_SECTION"
        | "ZENDESK_ARTICLE_CATEGORY"
        | "CONFLUENCE_PAGE"
        | "CONFLUENCE_SPACE"
        | "JIRA_TICKET"
        | "JIRA_PROJECT"
        | "SALESFORCE_TASK"
        | "BOX_FILE"
        | "BOX_FOLDER"
        | "NOTION_PAGE"
        | "NOTION_DATABASE"
        | "SLACK_CHANNEL"
        | "MONGO_COLLECTION_SYNC"
        | "UNKNOWN";
}
