/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Credal from "../../../../api/index";
import * as core from "../../../../core";

export const Role: core.serialization.Schema<serializers.Role.Raw, Credal.Role> = core.serialization.enum_([
    "viewer",
    "editor",
]);

export declare namespace Role {
    export type Raw = "viewer" | "editor";
}
